CREATE TABLE IF NOT EXISTS ACCOUNT(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    BALANCE DECIMAL
);

CREATE TABLE IF NOT EXISTS GAS_READING(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT_ID BIGINT,
    METER_ID INT,
    READING INT,
    DATE DATE NOT NULL,
    --USAGE_SINCE_LAST_READING INT,
    --PERIOD_SINCE_LAST_READING INT,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);

CREATE TABLE IF NOT EXISTS ELEC_READING(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT_ID BIGINT,
    METER_ID INT,
    READING INT,
    DATE DATE NOT NULL,
    --USAGE_SINCE_LAST_READING INT,
    --PERIOD_SINCE_LAST_READING INT,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);
